apiVersion: apps/v1
kind: Deployment

metadata:
  name: online-shop-deployment
  namespace: online-shop-ns
  labels:
    app: online-shop-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-shop-app

  template:
    metadata:
      name: online-shop-pod
      namespace: online-shop-ns
      labels:
        app: online-shop-app
    spec:
      containers:
      - name: online-shop-container
        image: hamzadevops01/online-shop-app:latest
        ports:
        - containerPort: 5173

